version: '3.6'

services:
    mongodb:
        image: mongo:4
        container_name: mongodb
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: 'root'
            MONGO_INITDB_ROOT_PASSWORD: 'password'
            MONGO_INITDB_DATABASE: 'fcontroller'
        ports:
            - 127.0.0.1:27020:27017
